version: '3.8'

services:
  db:
    image: mongodb/mongodb-atlas-local
    container_name: db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: retroboard
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./data/mongo/db:/data/db
      - ./data/mongo/config:/data/configdb
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000" # Map appropriate ports
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    environment:
      - GO_ENV=development
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080" # Map appropriate ports
    restart: always
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend