root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
[log]
  level = "debug"
  color = true